### ISSUE TITLE
[Feature Request]Support Immersive Engineering and Immersive Petroleum's mineral

### ISSUE THREAD

**Issue by mczph** [kumquat-ir/VisualOres#1]
When you pick up a Core Sample,the mineral type should be overlay on the map just like gtceu ones.

**Comment by kumquat-ir** [comment]
This is already planned to be implemented in a future update, along with thaumcraft aura/flux levels, astral starlight levels, and astral neromantic prime fluid veins.

**Comment by mczph** [comment]
@kumquat-ir Looks like 0.2.0 has this feature done, but why is it not on curseforge

**Comment by kumquat-ir** [comment]
Because curseforge is being very slow to approve it. For now you can grab a jar from github releases or modrinth. (also i forgot to close this, since its done now)
