### ISSUE TITLE
An option to add outline/border to ore icons on the map?

### ISSUE THREAD

**Issue by alfuken** [kumquat-ir/VisualOres#10]
So this is the first thing I've noticed when I've started using this cool mod: ore icons on the map are sometimes very hard to distinguish. For example:

Journeymap
<img width="374" alt="Screenshot 2024-02-19 at 03 06 42" src="https://github.com/kumquat-ir/VisualOres/assets/75377/3c5037e2-f252-48c9-8308-dcfab5483675">

Xaero
<img width="422" alt="Screenshot 2024-02-19 at 03 06 24" src="https://github.com/kumquat-ir/VisualOres/assets/75377/8d1ba5cd-774b-45ff-8063-8391b26cf612">

Would be awesome if you could add an option to add a contrast border to the icons on the map. At least letting the user chose between white and black, or allowing to specify the colour in RGB (say, 0-255 or 0.0-1.0). Or even with an extra option to have inverted colours (like that crosshair cursor in the game in the centre of the screen). But having at least black/white option would already help a lot :)

On a side note, `enableMinimapRendering` doesn't seem to work with `Xaeros_Minimap_23.9.7_Forge_1.12`

Also, how does the `oreScaleStop` configuration works? the description is kinda cryptic...

**Comment by kumquat-ir** [comment]
A border could definitely be added, probably as a config with an RGBA value.
Minimap rendering not working with recent versions of xaeros map is a known issue, I just haven't gotten around to looking into it yet.
`oreScaleStop` changes the point at which the ore icons stop scaling when you zoom in/out on the map.
(I really need to get to working on VO again...)

**Comment by kumquat-ir** [comment]
minimap 23.9.0, world map 1.37.0

**Comment by kumquat-ir** [comment]
Yes, that is setting the alpha (transparency) to 0. It needs to start with `FF` instead of `00`.
