### ISSUE TITLE
Weird visual bug with Xaero map overlay

### ISSUE THREAD

**Issue by alfuken** [kumquat-ir/VisualOres#11]
Basically, video is worth more than any words: https://drive.google.com/file/d/1C7bn9mXPQ9yZQkXcKCyXwnsHjOIU2R2u/view?usp=share_link

More system info and beginning of launcher log: https://pastebin.com/P7fRBVvA

**Comment by kumquat-ir** [comment]
Try updating Xaero's map to the latest version (or downgrading vo to 0.2.4), vo 0.2.5 has some changes to make it work with latest Xaero's that could cause weird rendering issues on older versions
