### ISSUE TITLE
Vein info cache fails to generate when non-gt ores are used

### ISSUE THREAD

**Issue by Teteros** [kumquat-ir/VisualOres#3]
video:
[![Watch the video](https://github-production-user-asset-6210df.s3.amazonaws.com/5067989/261838777-d86f049f-3b70-43ae-ad27-80ef16e2d186.png)](https://files.catbox.moe/l7brqn.webm)

- surface rocks can't be picked up and don't get prospected (reminds me of spawn protection, but this is singleplayer)
- gregtech ore scanners are the only thing that can show the VO prospect messages, but once prospected JourneyMap cannot be opened
- right clicking gregtech ores does nothing

Adding mods individually in a fresh instance, I've narrowed the mods causing it to be some sort of interaction between VisualOres, TFC Florae and the TFG coremod.
- TerraFirmaCraft 1.7.23.181 with gt worldgen vein config works fine with VO
- ~~TFC Florae~~ - doesn't start with TFC 1.7.23.181
- ~~TerraFirmaCraft 1.7.23.179~~ cannot test (gt ores don't spawn even with the worldgen vein config)
- TFG Coremod - seems to fix TFC Florae to work with 1.7.23.181 but has the issues mentioned

What's even more bizarre is that VisualOres never worked for me or my friend on Linux in this modpack (throwing opengl errors) but when I try Windows, VO sometimes works as intended, but I have no clue what makes it work. Spawning into a new world and trying to picking up a gt surface rock usually breaks it, but sometimes if I then reset VO with `/vo resetClientCache` and use an LV Ore Scanner instead, it can make VO work. LV in particular since that seems to have a better chance as VO is maybe breaking journeymap if it prospects more than one ore vein at a time.

full log: [latest.log](https://github.com/kumquat-ir/VisualOres/files/12387617/latest.log)

TFG devs didn't open source their coremod so I can't dig deeper than this but it's worth reporting still I think
Looking through the log, the issue might be with VO not being able to discover the ores added by TFG coremod
cc @SpeeeDCraft

**Comment by kumquat-ir** [comment]
first problem i noticed is that i am probably not handling materials registered by addons correctly, causing things to go wrong pretty early on and not populating the ore info cache, causing things to not get prospected via block/surface rock and if they end up in the map, the map will error and not open. will try to fix this, this looks like its the cause of all the errors.

if you can send a log with the opengl errors i can try to debug those, but that may also be caused by the above issue

**Comment by kumquat-ir** [comment]
can you try with this version of VO? (the jar is in the zip, github doesnt let you upload jars) @Teteros 
[visualores-0.2.2-pre.zip](https://github.com/kumquat-ir/VisualOres/files/12389038/visualores-0.2.2-pre.zip)

**Comment by Teteros** [comment]
log for visualores-0.2.2-pre https://mclo.gs/mTPfdN2#L6158
I don't see any difference in the errors printed from last log (other than the version change) for this build

**Comment by Teteros** [comment]
Fixed by 6452aa8 Thanks!
(the issue was that vein info cache did not want to generate when you had non-gregtech blocks in the gregtech worldgen json's config folder.
