### ISSUE TITLE
No Immersive Petroleum feature

### ISSUE THREAD

**Issue by Krutoy242** [kumquat-ir/VisualOres#4]
Immersive Petroleum installed, but there is no button to show overlay for that

![image](https://github.com/kumquat-ir/VisualOres/assets/936618/13119ca4-7222-44d1-a668-909551dc5850)

[debug.log](https://github.com/kumquat-ir/VisualOres/files/12496887/debug.log)

**Comment by kumquat-ir** [comment]
The Immersive Petroleum information is shown along with the excavator veins, the information added to the map is exactly what is on the tooltip of the core sample you pick up. It's the "5,713,000 mB Oil" line in this screenshot.
![2023-07-31_15 18 05](https://github.com/kumquat-ir/VisualOres/assets/66188216/c5c0b13d-f5ae-4f2b-9c7b-c900a2ef241c)

**Comment by Krutoy242** [comment]
Ok, thank you. I wish there was coloured boxes instead of just text

**Comment by kumquat-ir** [comment]
ill add that to my todo list, seems like a good idea
