### ISSUE TITLE
Minimap incorrectly synced with overlay

### ISSUE THREAD

**Issue by Krutoy242** [kumquat-ir/VisualOres#6]
When overlay is enabled, minimap synced incorrectly:

https://github.com/kumquat-ir/VisualOres/assets/936618/f576183c-2e84-49ab-ab32-727fb9f9f1f8

This not happens if zoom is out

https://github.com/kumquat-ir/VisualOres/assets/936618/c25a0667-5d46-454d-8014-2c613024e366

[debug.log](https://github.com/kumquat-ir/VisualOres/files/12496911/debug.log)

**Comment by kumquat-ir** [comment]
could have sworn i tested this... will be fixed in the next release
