### ISSUE TITLE
GT Ore scanning does not fully work with Simple Vein type

### ISSUE THREAD

**Issue by Delfayne** [kumquat-ir/VisualOres#8]
While it works lovely with Layered veins, Simple veins don't scan all the blocks in the vein, not show textures on the map (though the tooltip is accessible if you hover over an "invisible" vein).

Simple veins can have multiple ores with % weighting. Visual Ores stops at the first, and shows no texture: 
![image](https://github.com/kumquat-ir/VisualOres/assets/97418063/1ee17fd5-0521-46ad-a7eb-4fb41a025a1b)

**Comment by kumquat-ir** [comment]
yeah,,, simple veins are a lot harder to work with from a code perspective so I just put off dealing with them
I guess I'll have to look at how the JEI page handles them, and actually add code for setting an icon for non-layered veins
