### ISSUE TITLE
[feature request] Config to allow changing block-to-ore mapping

### ISSUE THREAD

**Issue by alfuken** [kumquat-ir/VisualOres#9]
I'm making a Gregtech modpack with emphasis on [Geobotanical prospecting](https://en.wikipedia.org/wiki/Geobotanical_prospecting), where, unlike vanilla GT, which spawn dust piles on the surface, I'm using flowers from the [Plants](https://www.curseforge.com/minecraft/mc-mods/plants) mod to indicate ore deposits. For example, beryllium is indicated by a Aloe Ballii plant on the surface:

```
  "vein_populator": {
    "type": "surface_block",
    "block": {
      "block": "plants2:cosmetic_1",
      "type": "aloe_b"
    },
    "min_amount": 2,
    "max_amount": 4
  },
```

which [looks like this](https://github.com/Shadows-of-Fire/Plants/wiki/Aloe-Ballii),
and [redstone - by Aechmea Amicorum](https://github.com/Shadows-of-Fire/Plants/wiki/Aechmea-Amicorum):
```
  "vein_populator": {
    "type": "surface_block",
    "block": {
      "block": "plants2:cosmetic_0",
      "type": "aechmea_a"
    },
    "min_amount": 2,
    "max_amount": 4
  },
```

I tried to figure out logic that VisualOres uses to detect deposit type and to add a map icons/waypoints, but my Java knowledge is not that good yet.

It would be awesome if you could add possibility to configure the connection between block clicked and deposit marked. :)

**Comment by kumquat-ir** [comment]
VO adds ore veins to the map when you either: pick up a surface rock, r-click an ore block, or use the electric prospector.
The click events are currently handled by mixining block click methods into the appropriate block classes, which isn't very expandable. I might look into being able to specify block -> ore vein mapping on click, though no promises on when that will happen since I haven't had too much motivation to work on VO recently.

**Comment by kumquat-ir** [comment]
Looks like the best way with code that currently exists is to call [`ServerCache.instance.prospectOreBlock`](https://github.com/kumquat-ir/VisualOres/blob/master/src/main/java/hellfall/visualores/database/gregtech/ore/ServerCache.java#L65) with the current dimension, the result of `material.getResourceLocation().toString()` on the GT material you want to simulate an ore block click for, the `BlockPos` of the position where it was clicked, and the radius (in blocks) to look for veins in.

Best way to make it easier with adding code to VO would be storing the deposit name in `OreVeinInfo` as well and adding a similar method to `prospectOreBlock` to `ServerCache`, which you could then call with the result of looking up what deposit name corresponds with which flower.

**Comment by kumquat-ir** [comment]
That event is actually fired on both client and server side, so you should be able to check which side its being fired on with `event.getSide()` and only call `prospectOreBlock` if it is `Side.SERVER`.
